language = "C++"
include_guard = "AVIF_H"
tab_width = 4
usize_is_size_t = true
namespace = "crabbyavif"

[export.rename]
"ChromaDownsampling" = "avifChromaDownsampling"
"ChromaSamplePosition" = "avifChromaSamplePosition"
"ChromaUpsampling" = "avifChromaUpsampling"
"ColorPrimaries" = "avifColorPrimaries"
"Format" = "avifRGBFormat"
"IOStats" = "avifIOStats"
"ImageTiming" = "avifImageTiming"
"MatrixCoefficients" = "avifMatrixCoefficients"
"PixelFormat" = "avifPixelFormat"
"ProgressiveState" = "avifProgressiveState"
"ScalingMode" = "avifScalingMode"
"Source" = "avifDecoderSource"
"YuvRange" = "avifRange"
"TransferCharacteristics" = "avifTransferCharacteristics"
"AVIF_DIAGNOSTICS_ERROR_BUFFER_SIZE" = "CRABBY_AVIF_DIAGNOSTICS_ERROR_BUFFER_SIZE"
"AVIF_FALSE" = "CRABBY_AVIF_FALSE"
"AVIF_PLANE_COUNT_YUV" = "CRABBY_AVIF_PLANE_COUNT_YUV"
"AVIF_REPETITION_COUNT_INFINITE" = "CRABBY_AVIF_REPETITION_COUNT_INFINITE"
"AVIF_REPETITION_COUNT_UNKNOWN" = "CRABBY_AVIF_REPETITION_COUNT_UNKNOWN"
"AVIF_TRUE" = "CRABBY_AVIF_TRUE"
"DEFAULT_IMAGE_COUNT_LIMIT" = "CRABBY_AVIF_DEFAULT_IMAGE_COUNT_LIMIT"
"DEFAULT_IMAGE_DIMENSION_LIMIT" = "CRABBY_AVIF_DEFAULT_IMAGE_DIMENSION_LIMIT"
"DEFAULT_IMAGE_SIZE_LIMIT" = "CRABBY_AVIF_DEFAULT_IMAGE_SIZE_LIMIT"
"MAX_AV1_LAYER_COUNT" = "CRABBY_AVIF_MAX_AV1_LAYER_COUNT"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
enum_class = false

[export]
include = [
  "avifChannelIndex",
  "avifCodecFlag",
  "avifCodecFlags",
  "avifHeaderFormat",
  "avifPlanesFlag",
  "avifPlanesFlags",
  "avifStrictFlag",
  "AVIF_COLOR_PRIMARIES_BT709",
]
exclude = ["Box"]
