use rust_libavif::decoder::AvifImage;
use rust_libavif::decoder::AvifImageInfo;
use rust_libavif::*;

use std::fs::remove_file;
use std::fs::File;
use std::io::BufReader;
use std::io::Read;
use std::process::Command;
use tempfile::NamedTempFile;

const TEST_DATA_PATH: &str = "/Users/vigneshv/code/av1-avif/testFiles";

#[derive(Copy, Clone)]
struct ExpectedAvifImageInfo<'a> {
    filename: &'a str,
    width: u32,
    height: u32,
    depth: u8,
    yuv_format: PixelFormat,
    alpha_present: bool,
    full_range: bool,
    #[allow(unused)]
    color_primaries: u16,
    #[allow(unused)]
    transfer_characteristics: u16,
    #[allow(unused)]
    matrix_coefficients: u16,
}

fn verify_info(expected_info: &ExpectedAvifImageInfo, info: &AvifImageInfo) {
    assert_eq!(info.width, expected_info.width);
    assert_eq!(info.height, expected_info.height);
    assert_eq!(info.depth, expected_info.depth);
    assert_eq!(info.yuv_format, expected_info.yuv_format);
    assert_eq!(info.alpha_present, expected_info.alpha_present);
    assert_eq!(info.full_range, expected_info.full_range);
    assert_eq!(info.color_primaries, expected_info.color_primaries);
    assert_eq!(
        info.transfer_characteristics,
        expected_info.transfer_characteristics
    );
    assert_eq!(info.matrix_coefficients, expected_info.matrix_coefficients);
}

fn get_tempfile() -> String {
    let file = NamedTempFile::new().expect("unable to open tempfile");
    let path = file.into_temp_path();
    let filename = String::from(path.to_str().unwrap());
    let _ = path.close();
    println!("### filename: {:#?}", filename);
    filename
}

fn write_y4m(image: &AvifImage) -> String {
    let filename = get_tempfile();
    let mut y4m = rust_libavif::utils::Y4MWriter::create(&filename);
    assert!(y4m.write_frame(image));
    filename
}

fn run_avifdec(filename: &String) -> String {
    let mut outfile = get_tempfile();
    outfile.push_str(".y4m");
    let avifdec = Command::new("/opt/homebrew/bin/avifdec")
        .arg("--no-strict")
        .arg("--jobs")
        .arg("8")
        .arg(filename)
        .arg(&outfile)
        .output()
        .unwrap();
    println!("avifdec: {:#?}", avifdec);
    assert!(avifdec.status.success());
    outfile
}

fn compare_files(file1: &String, file2: &String) -> bool {
    let f1 = File::open(file1).unwrap();
    let f2 = File::open(file2).unwrap();
    if f1.metadata().unwrap().len() != f2.metadata().unwrap().len() {
        return false;
    }
    let f1 = BufReader::new(f1);
    let f2 = BufReader::new(f2);
    for (byte1, byte2) in f1.bytes().zip(f2.bytes()) {
        if byte1.unwrap() != byte2.unwrap() {
            return false;
        }
    }
    true
}

fn decode_and_verify(expected_info: &ExpectedAvifImageInfo) {
    let filename = String::from(format!("{TEST_DATA_PATH}/{}", expected_info.filename));
    let mut decoder = decoder::AvifDecoder::default();
    let _ = decoder.set_io_file(&filename).expect("Failed to set IO");
    let res = decoder.parse();
    assert!(res.is_ok());
    let info = res.unwrap();
    verify_info(expected_info, info);
    let res = decoder.next_image();
    assert!(res.is_ok());
    let image = res.unwrap();
    // Link-U 422 files have wrong subsampling in the Avif header(decoded one
    // is right).
    if !filename.contains("Link-U") || !filename.contains("yuv422") {
        verify_info(expected_info, &image.info);
    }

    // Write y4m.
    let y4m_file = write_y4m(image);
    // Write y4m by invoking avifdec.
    let gold_y4m_file = run_avifdec(&filename);
    // Compare.
    assert!(compare_files(&y4m_file, &gold_y4m_file));
    let _ = remove_file(y4m_file);
    let _ = remove_file(gold_y4m_file);
}

// If more files are added to this array, update the call to generate_tests macro below.
const EXPECTED_INFOS: [ExpectedAvifImageInfo; 172] = [
    // index: 0
    ExpectedAvifImageInfo {
        filename: "Apple/edge_case_testing/non_compliant/truncated_elementary_stream.avif",
        width: 1024,
        height: 768,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 1
    ExpectedAvifImageInfo {
        filename: "Apple/edge_case_testing/unknown_properties/free_property.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 2
    ExpectedAvifImageInfo {
        filename: "Apple/edge_case_testing/unknown_properties/unknown_nonessential_property.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 3
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_a1lx.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 4
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_a1op.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 5
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_a1op_lsel.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 6
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_grid_a1lx.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 7
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_grid_lsel.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 8
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_lsel.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 9
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_singlelayer.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 10
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 11
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 12
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 13
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 14
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 15
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 16
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 17
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 18
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 19
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 20
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 21
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 22
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 23
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 24
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 25
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 26
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 27
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 28
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 29
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 30
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 31
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 32
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 33
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 34
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 35
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 36
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 37
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 38
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 39
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 40
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 41
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 42
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 43
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 44
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 45
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 46
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 47
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 48
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 49
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 50
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 51
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 52
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 53
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 54
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 55
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 56
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 57
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 58
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 59
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 60
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 61
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 62
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 63
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 64
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 65
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 66
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 67
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 68
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 69
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 70
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 71
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 72
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 73
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 74
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.10bpc.yuv420.monochrome.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 75
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.10bpc.yuv420.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 76
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.8bpc.yuv420.monochrome.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 77
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.8bpc.yuv420.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 78
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.10bpc.yuv422.monochrome.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 79
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.10bpc.yuv422.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 80
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.12bpc.yuv422.monochrome.avif",
        width: 3082,
        height: 2048,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 2,
        matrix_coefficients: 9,
    },
    // index: 81
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.12bpc.yuv422.monochrome.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 82
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.12bpc.yuv422.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 83
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.8bpc.yuv422.monochrome.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 84
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.8bpc.yuv422.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 85
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 86
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.crop.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 87
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-horizontal.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 88
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-vertical.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 89
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-vertical.rotate270.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 90
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-vertical.rotate270.crop.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 91
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.rotate270.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 92
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.rotate90.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    // index: 93
    ExpectedAvifImageInfo {
        filename: "Microsoft/Chimera_10bit_cropped_to_1920x1008.avif",
        width: 1920,
        height: 1080,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 94
    ExpectedAvifImageInfo {
        filename: "Microsoft/Chimera_10bit_cropped_to_1920x1008_with_HDR_metadata.avif",
        width: 1920,
        height: 1080,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 10,
    },
    // index: 95
    ExpectedAvifImageInfo {
        filename: "Microsoft/Chimera_8bit_cropped_480x256.avif",
        width: 480,
        height: 270,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 96
    ExpectedAvifImageInfo {
        filename: "Microsoft/Irvine_CA.avif",
        width: 480,
        height: 640,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 97
    ExpectedAvifImageInfo {
        filename: "Microsoft/Mexico.avif",
        width: 1920,
        height: 1080,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 98
    ExpectedAvifImageInfo {
        filename: "Microsoft/Mexico_YUV444.avif",
        width: 960,
        height: 540,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 99
    ExpectedAvifImageInfo {
        filename: "Microsoft/Monochrome.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 1,
        matrix_coefficients: 1,
    },
    // index: 100
    ExpectedAvifImageInfo {
        filename: "Microsoft/Ronda_rotate90.avif",
        width: 1920,
        height: 1080,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 101
    ExpectedAvifImageInfo {
        filename: "Microsoft/Summer_Nature_4k.avif",
        width: 3840,
        height: 2160,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 102
    ExpectedAvifImageInfo {
        filename: "Microsoft/Summer_in_Tomsk_720p_5x4_grid.avif",
        width: 6400,
        height: 2880,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 103
    ExpectedAvifImageInfo {
        filename: "Microsoft/Tomsk_with_thumbnails.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    // index: 104
    ExpectedAvifImageInfo {
        filename: "Microsoft/bbb_4k.avif",
        width: 3840,
        height: 2160,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 105
    ExpectedAvifImageInfo {
        filename: "Microsoft/bbb_alpha_inverted.avif",
        width: 3840,
        height: 2160,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: true,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    // index: 106
    ExpectedAvifImageInfo {
        filename: "Microsoft/kids_720p.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 107
    ExpectedAvifImageInfo {
        filename: "Microsoft/reduced_still_picture_header.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    // index: 108
    ExpectedAvifImageInfo {
        filename: "Microsoft/still_picture.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    // index: 109
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    // index: 110
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 111
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 112
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 113
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 114
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 115
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 116
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    // index: 117
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 118
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 119
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 120
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 121
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 122
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 123
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    // index: 124
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 125
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 126
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 127
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 128
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 129
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 130
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    // index: 131
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 132
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 133
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 134
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 135
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 136
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    // index: 137
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    // index: 138
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 139
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 140
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 141
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 142
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 143
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 144
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    // index: 145
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 146
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 147
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 148
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 149
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 150
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 151
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    // index: 152
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 153
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 154
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 155
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 156
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 157
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 158
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    // index: 159
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 160
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 161
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 162
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 163
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 164
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    // index: 165
    ExpectedAvifImageInfo {
        filename: "Netflix/avis/Chimera-AV1-10bit-480x270.avif",
        width: 480,
        height: 270,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 166
    ExpectedAvifImageInfo {
        filename: "Netflix/avis/alpha_video.avif",
        width: 640,
        height: 480,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: true,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    // index: 167
    ExpectedAvifImageInfo {
        filename: "Xiph/abandoned_filmgrain.avif",
        width: 1404,
        height: 936,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 168
    ExpectedAvifImageInfo {
        filename: "Xiph/fruits_2layer_thumbsize.avif",
        width: 1296,
        height: 864,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 169
    ExpectedAvifImageInfo {
        filename: "Xiph/quebec_3layer_op2.avif",
        width: 360,
        height: 182,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 170
    ExpectedAvifImageInfo {
        filename: "Xiph/tiger_3layer_1res.avif",
        width: 1216,
        height: 832,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    // index: 171
    ExpectedAvifImageInfo {
        filename: "Xiph/tiger_3layer_3res.avif",
        width: 1216,
        height: 832,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
];

macro_rules! generate_tests {
    ($size: expr) => {
        seq_macro::seq!(N in 0..$size {
            #(#[test_case::test_case(N)])*
            fn test_conformance(index: usize) {
                decode_and_verify(&EXPECTED_INFOS[index]);
            }
        });
    };
}

generate_tests!(172);
