use rust_libavif::*;

const TEST_DATA_PATH: &str = "/Users/vigneshv/code/av1-avif/testFiles";

/*
macro_rules! assert_avif_error {
    ($res:ident, $err:ident) => {
        assert!($res.is_err());
        assert!(matches!($res.err().unwrap(), AvifError::$err));
    };
}
*/

#[derive(Copy, Clone)]
struct ExpectedAvifImageInfo<'a> {
    filename: &'a str,
    width: u32,
    height: u32,
    depth: u8,
    yuv_format: PixelFormat,
    alpha_present: bool,
    full_range: bool,
    #[allow(unused)]
    color_primaries: u16,
    #[allow(unused)]
    transfer_characteristics: u16,
    #[allow(unused)]
    matrix_coefficients: u16,
}

fn decode_and_verify(expected_info: &ExpectedAvifImageInfo) {
    let filename = String::from(format!("{TEST_DATA_PATH}/{}", expected_info.filename));
    let mut decoder = decoder::AvifDecoder::default();
    let _ = decoder.set_io_file(&filename).expect("Failed to set IO");
    let res = decoder.parse();
    assert!(res.is_ok());
    let info = res.unwrap();
    assert_eq!(info.width, expected_info.width);
    assert_eq!(info.height, expected_info.height);
    assert_eq!(info.depth, expected_info.depth);
    assert_eq!(info.yuv_format, expected_info.yuv_format);
    assert_eq!(info.alpha_present, expected_info.alpha_present);
    assert_eq!(info.full_range, expected_info.full_range);
    // TODO: Fix these.
    if false {
        assert_eq!(info.color_primaries, expected_info.color_primaries);
        assert_eq!(
            info.transfer_characteristics,
            expected_info.transfer_characteristics
        );
        assert_eq!(info.matrix_coefficients, expected_info.matrix_coefficients);
    }
    let res = decoder.next_image();
    assert!(res.is_ok());
}

// If more files are added to this array, update the call to generate_tests macro below.
const EXPECTED_INFOS: [ExpectedAvifImageInfo; 172] = [
    ExpectedAvifImageInfo {
        filename: "Apple/edge_case_testing/non_compliant/truncated_elementary_stream.avif",
        width: 1024,
        height: 768,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/edge_case_testing/unknown_properties/free_property.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/edge_case_testing/unknown_properties/unknown_nonessential_property.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_a1lx.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_a1op.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_a1op_lsel.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_grid_a1lx.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_grid_lsel.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_multilayer_lsel.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Apple/multilayer_examples/animals_00_singlelayer.avif",
        width: 2048,
        height: 1536,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 12,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.10bpc.yuv420.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile0.8bpc.yuv420.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.10bpc.yuv444.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile1.8bpc.yuv444.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.10bpc.yuv422.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv420.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv422.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.12bpc.yuv444.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.avif",
        width: 1204,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.monochrome.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.odd-height.avif",
        width: 1204,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.odd-width.avif",
        width: 1203,
        height: 800,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/fox.profile2.8bpc.yuv422.odd-width.odd-height.avif",
        width: 1203,
        height: 799,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.10bpc.yuv420.monochrome.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.10bpc.yuv420.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.8bpc.yuv420.monochrome.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile0.8bpc.yuv420.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.10bpc.yuv422.monochrome.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.10bpc.yuv422.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.12bpc.yuv422.monochrome.avif",
        width: 3082,
        height: 2048,
        depth: 12,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 2,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.12bpc.yuv422.monochrome.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.12bpc.yuv422.no-cdef.no-restoration.avif",
        width: 3082,
        height: 2048,
        depth: 12,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.8bpc.yuv422.monochrome.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/hato.profile2.8bpc.yuv422.no-cdef.avif",
        width: 3082,
        height: 2048,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.crop.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-horizontal.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-vertical.avif",
        width: 722,
        height: 1024,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-vertical.rotate270.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.mirror-vertical.rotate270.crop.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.rotate270.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Link-U/kimono.rotate90.avif",
        width: 1024,
        height: 722,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Chimera_10bit_cropped_to_1920x1008.avif",
        width: 1920,
        height: 1080,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Chimera_10bit_cropped_to_1920x1008_with_HDR_metadata.avif",
        width: 1920,
        height: 1080,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 10,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Chimera_8bit_cropped_480x256.avif",
        width: 480,
        height: 270,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Irvine_CA.avif",
        width: 480,
        height: 640,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Mexico.avif",
        width: 1920,
        height: 1080,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Mexico_YUV444.avif",
        width: 960,
        height: 540,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Monochrome.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Monochrome,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 1,
        matrix_coefficients: 1,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Ronda_rotate90.avif",
        width: 1920,
        height: 1080,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Summer_Nature_4k.avif",
        width: 3840,
        height: 2160,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Summer_in_Tomsk_720p_5x4_grid.avif",
        width: 6400,
        height: 2880,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/Tomsk_with_thumbnails.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/bbb_4k.avif",
        width: 3840,
        height: 2160,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/bbb_alpha_inverted.avif",
        width: 3840,
        height: 2160,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: true,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/kids_720p.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: true,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/reduced_still_picture_header.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    ExpectedAvifImageInfo {
        filename: "Microsoft/still_picture.avif",
        width: 1280,
        height: 720,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01000_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos01650_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos07296_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 10,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 9,
        transfer_characteristics: 16,
        matrix_coefficients: 9,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01000_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos01650_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos07296_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-0_lossless.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 0,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv420_limited_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv420_limited_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv420_limited_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv444_full_qp10.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv444_full_qp20.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avif/sdr_cosmos12920_cicp1-13-6_yuv444_full_qp40.avif",
        width: 2048,
        height: 858,
        depth: 8,
        yuv_format: PixelFormat::Yuv444,
        alpha_present: false,
        full_range: true,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 6,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avis/Chimera-AV1-10bit-480x270.avif",
        width: 480,
        height: 270,
        depth: 10,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Netflix/avis/alpha_video.avif",
        width: 640,
        height: 480,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: true,
        full_range: false,
        color_primaries: 1,
        transfer_characteristics: 13,
        matrix_coefficients: 1,
    },
    ExpectedAvifImageInfo {
        filename: "Xiph/abandoned_filmgrain.avif",
        width: 1404,
        height: 936,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Xiph/fruits_2layer_thumbsize.avif",
        width: 1296,
        height: 864,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Xiph/quebec_3layer_op2.avif",
        width: 360,
        height: 182,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Xiph/tiger_3layer_1res.avif",
        width: 1216,
        height: 832,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
    ExpectedAvifImageInfo {
        filename: "Xiph/tiger_3layer_3res.avif",
        width: 1216,
        height: 832,
        depth: 8,
        yuv_format: PixelFormat::Yuv420,
        alpha_present: false,
        full_range: false,
        color_primaries: 2,
        transfer_characteristics: 2,
        matrix_coefficients: 2,
    },
];

macro_rules! generate_tests {
    ($size: expr) => {
        seq_macro::seq!(N in 0..$size {
            #(#[test_case::test_case(N)])*
            fn test_conformance(index: usize) {
                decode_and_verify(&EXPECTED_INFOS[index]);
            }
        });
    };
}

generate_tests!(172);
