name: "Set up the dependencies"
description: "Build all the necessary external dependencies"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

  - name: Set globals
    id: globals
    shell: bash
    run: echo "AV1_AVIF_COMMIT_HASH=aa906e00c9d8655a8b97718aa16d379970678663" >> "${GITHUB_OUTPUT}"

  - name: Setup Visual Studio shell
    if: runner.os == 'Windows'
    uses: egor-tensin/vs-shell@9a932a62d05192eae18ca370155cf877eecc2202 # v2.1

  - name: Cache external dependencies
    id: cache-ext
    uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
    with:
      path: |
        sys/dav1d-sys/dav1d/include
        sys/dav1d-sys/dav1d/build/include/dav1d
        sys/dav1d-sys/dav1d/build/src
        sys/libyuv-sys/libyuv/include
        sys/libyuv-sys/libyuv/build
        sys/aom-sys/aom/aom
        sys/aom-sys/aom/build.libavif
        sys/libsharpyuv-sys/libwebp/sharpyuv
        sys/libsharpyuv-sys/libwebp/build
        external/googletest
        sys/libpng-sys
      key: cache-ext-${{ github.job }}-${{ runner.os }}-${{ hashFiles('.github/actions/setup-deps/action.yml', 'sys/dav1d-sys/**', 'sys/libyuv-sys/**', 'sys/aom-sys/**', 'sys/libsharpyuv-sys/**', 'external/googletest.cmd', 'sys/libpng-sys/**') }}

  - name: Cache av1-avif testFiles
    id: cache-av1-avif-testfiles
    uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
    with:
      path: external/av1-avif/testFiles
      key: cache-av1-avif-testfiles-${{ steps.globals.outputs.AV1_AVIF_COMMIT_HASH }}
      enableCrossOsArchive: true

  - uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
    if: steps.cache-ext.outputs.cache-hit != 'true'
  - uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2
    if: steps.cache-ext.outputs.cache-hit != 'true'
  - uses: seanmiddleditch/gha-setup-ninja@3b1f8f94a2f8254bd26914c4ab9474d4f0015f67 # v6
    if: steps.cache-ext.outputs.cache-hit != 'true'
  - run: pip install meson
    if: steps.cache-ext.outputs.cache-hit != 'true'
    shell: bash
  - name: Build dav1d
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/dav1d-sys
    run: ./dav1d.cmd
    shell: bash
  - name: Build libyuv
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/libyuv-sys
    run: ./libyuv.cmd
    shell: bash
  - name: Build aom
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/aom-sys
    run: ./aom.cmd
    shell: bash
  - name: Build sharpyuv
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/libsharpyuv-sys
    run: ./libsharpyuv.cmd
    shell: bash
  - name: Build GoogleTest
    if: steps.cache-ext.outputs.cache-hit != 'true' && runner.os != 'Windows'
    working-directory: ./external
    run: ./googletest.cmd
    shell: bash
  - name: Build libpng (non Windows)
    if: steps.cache-ext.outputs.cache-hit != 'true' && runner.os != 'Windows'
    working-directory: ./sys/libpng-sys
    run: ./zlibpng.cmd
    shell: bash
  - name: Build libpng (Windows)
    if: steps.cache-ext.outputs.cache-hit != 'true' && runner.os == 'Windows'
    working-directory: ./sys/libpng-sys
    run: ./zlibpng_windows.cmd
    shell: bash
  - name: Clone av1-avif (specification repository for testFiles)
    if: steps.cache-av1-avif-testfiles.outputs.cache-hit != 'true'
    working-directory: ./external
    run: |
      git clone https://github.com/AOMediaCodec/av1-avif.git
      cd av1-avif
      git checkout ${{ steps.globals.outputs.AV1_AVIF_COMMIT_HASH }}
    shell: bash
  - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
    with:
      toolchain: stable
