name: "Set up the dependencies"
description: "Build all the necessary external dependencies"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

  - name: Setup Visual Studio shell
    if: runner.os == 'Windows'
    uses: egor-tensin/vs-shell@9a932a62d05192eae18ca370155cf877eecc2202 # v2.1

  - name: Cache external dependencies
    id: cache-ext
    uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
    with:
      path: |
        sys
        external
      key: ${{ runner.os }}-${{ hashFiles('sys/dav1d-sys/Cargo.toml', 'sys/dav1d-sys/dav1d.cmd', 'sys/dav1d-sys/build.rs', 'sys/libyuv-sys/Cargo.toml', 'sys/libyuv-sys/libyuv.cmd', 'sys/libyuv-sys/build.rs', 'external/googletest.cmd', 'sys/aom-sys/Cargo.toml', 'sys/aom-sys/aom.cmd', 'sys/aom-sys/build.rs', 'sys/libsharpyuv-sys/Cargo.toml', 'sys/libsharpyuv-sys/libsharpyuv.cmd', 'sys/libsharpyuv-sys/build.rs', 'sys/libpng-sys/Cargo.toml', 'sys/libpng-sys/zlibpng.cmd', 'sys/libpng-sys/build.rs') }}

  - uses: jwlawson/actions-setup-cmake@d06b37b47cfd043ec794ffa3e40e0b6b5858a7ec # v1.14.2
    if: steps.cache-ext.outputs.cache-hit != 'true'
  - uses: ilammy/setup-nasm@13cbeb366c45c4379d3478cdcbadd8295feb5028 # v1.5.1
    if: steps.cache-ext.outputs.cache-hit != 'true'
  - uses: seanmiddleditch/gha-setup-ninja@8b297075da4cd2a5f1fd21fe011b499edf06e9d2 # v4
    if: steps.cache-ext.outputs.cache-hit != 'true'
  - run: pip install meson
    if: steps.cache-ext.outputs.cache-hit != 'true'
    shell: bash
  - name: Build dav1d
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/dav1d-sys
    run: ./dav1d.cmd
    shell: bash
  - name: Build libyuv
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/libyuv-sys
    run: ./libyuv.cmd
    shell: bash
  - name: Build aom
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/aom-sys
    run: ./aom.cmd
    shell: bash
  - name: Build sharpyuv
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./sys/libsharpyuv-sys
    run: ./libsharpyuv.cmd
    shell: bash
  - name: Build GoogleTest
    if: steps.cache-ext.outputs.cache-hit != 'true' && runner.os != 'Windows'
    working-directory: ./external
    run: ./googletest.cmd
    shell: bash
  - name: Build libpng (non Windows)
    if: steps.cache-ext.outputs.cache-hit != 'true' && runner.os != 'Windows'
    working-directory: ./sys/libpng-sys
    run: ./zlibpng.cmd
    shell: bash
  - name: Build libpng (Windows)
    if: steps.cache-ext.outputs.cache-hit != 'true' && runner.os == 'Windows'
    working-directory: ./sys/libpng-sys
    run: ./zlibpng_windows.cmd
    shell: bash
  - name: Clone av1-avif (specification repository for testFiles)
    if: steps.cache-ext.outputs.cache-hit != 'true'
    working-directory: ./external
    run: |
      git clone https://github.com/AOMediaCodec/av1-avif.git
      cd av1-avif
      git checkout aa906e00c9d8655a8b97718aa16d379970678663
    shell: bash
  - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
    with:
      toolchain: stable
