name: Build and Run Tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

# Cancel the workflow if a new one is triggered from the same PR, branch, or tag, except on main.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-run-tests:
    name: "Build and Run Tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - uses: ./.github/actions/setup-deps

    - name: Print A
      run: ls sys
      continue-on-error: true

    - name: Print B
      run: ls sys/dav1d-sys
      continue-on-error: true

    - name: Print C
      run: ls sys/dav1d-sys/dav1d
      continue-on-error: true

    - name: Print D
      run: ls sys/dav1d-sys/dav1d/build
      continue-on-error: true

    - name: Print E
      run: ls sys/dav1d-sys/dav1d/build/src
      continue-on-error: true

    - name: Print F
      run: ls sys/libwebp
      continue-on-error: true

    - name: Print G
      run: ls sys/libwebp/build
      continue-on-error: true

    - name: Build and run the Rust tests
      run: cargo test

    - name: Build and run the C++ tests
      # TODO: This step fails on macos. So run it on linux only for now.
      if: runner.os == 'Linux'
      run: |
        cargo build --features capi,aom --release
        cmake -S c_api_tests -B c_build
        make -C c_build
        ctest --test-dir c_build


    - name: Build and run the heic tests with heic feature enabled
      run: cargo test --features heic heic

    - name: Build and run all the tests with aom feature enabled
      # TODO: Enable this for windows.
      if: runner.os != 'Windows'
      run: cargo test --features aom
